export const designTokens = {
    space: {
        xxs: 4,
        xs: 8,
        sm: 12,
        base: 16,
        md: 24,
        lg: 32,
        xl: 48,
        xxl: 64,
        '3xl': 96,
        '4xl': 128,
        '5xl': 192,
    },
    strokeWidth: {
        sm: 1,
        md: 2,
        lg: 4,
    },
    color: {
        black: '#000000',
        people: '#E8493D',
        planet: '#AB59A3',
        profit: '#12AA5A',
        northAmerica: '#F2724F',
        europe: '#fec72f',
        asia: '#B6DFCD',
        oceania: '#A29DCD',
        middleEast: '#9BD1E5',
        africa: '#FFCFD2',
        southAmerica: '#FAF3DD',
    },
    borderRadius: {
        sm: 2,
        md: 4,
        lg: 8,
    },
    boxShadow: {
        sm: '4px 4px 0px 0px #000',
        md: '8px 8px 0px 0px #000',
        lg: '12px 12px 0px 0px #000',
    },
}
